### ISSUE TITLE
5.Strings/5.3/BoyerMoore.java

### ISSUE THREAD

**Issue by zxt385189207** [HuangStomach/algorithm#1]
private Queue<Integer> all(String txt) {
        Queue<Integer> queue = new Queue<Integer>();
        int N = txt.length();
        int M = pat.length();
        int skip;
        for (int i = 0; i <= N - M; i += skip) {
            skip = 0;
            for (int j = M - 1; j >= 0; j--) {
                if (pat.charAt(j) != txt.charAt(i + j)) {
                    skip = j - right[txt.charAt(i + j)];
                    if (skip < 1) skip = 1;
                    break;
                }
            }

            if (skip == 0) queue.enqueue(i);  // 死循环了.  加句skip =1;
        }
        return queue;
    }

**Comment by HuangStomach** [comment]
@zxt385189207 多谢指正
